Eco-Colocation/Controllers/Ad_CreationProjectController.cs
using System.Web.Mvc;

namespace Eco_Colocation.Controllers
{
	public class Ad_CreationProjectController : Controller
	{
        // GET: Ad_CreationProject
        public ActionResult Index()
        {
            return View();
        }

		public ActionResult AddUpd_ModalCreationProjectAd(string operation)
		{
			if (operation != null)
			{
				ViewData["operation"] = operation;
			}

			return PartialView();
		}

		public ActionResult Del_MsgModalCreationProjectAd()
		{
			return PartialView();
		}
		
		public ActionResult Read_ModalCreationProjectAd(string idModal)
		{
			ViewData["targetCity"] = "Rennes";
			ViewData["IdModal"] = idModal;

			return PartialView();
		}

		public ActionResult DeleteProjectCreation()
		{
			//** A faire : Supprimer l'annonce **//

			return RedirectToAction("CommonAd", "Home", new { currentTab = "ProjetCreation", researchType = "offering" });
		}
	}
}

Eco-Colocation/Views/Ad_CreationProject/CreationProjectView.cshtml
@{
	ViewBag.Title = "CreationProjectView";
}

@if (ViewBag.researchType == "searching")
{
	<div id="lstCreationProjectAd-cpv"></div>
}
else if (ViewBag.researchType == "offering")
{
	<div id="div1-2-ProjetCreation-al">
		<a href="@Url.Action("AddUpd_ModalCreationProjectAd", "Ad_CreationProject", null)" rel="modal:open">
			<div id="btnCreer-al" class="createProjetCreationLink-al">Creer un projet de création</div>
		</a>
	</div>
	if (User.Identity.IsAuthenticated)
	{
		<div id="lstCreationProjectAd-cpv"></div>
	}
}

<div id="projetCreationAnnounce">
	<div class="flex childFlex divHighterProjetCreationPVLink">
		@if (User.Identity.IsAuthenticated & ViewBag.researchType == "offering")
		{
			<div class="divToolEditProjetCreation-al">
				<a href="@Url.Action("AddUpd_ModalCreationProjectAd", "Ad_CreationProject", null)" rel="modal:open" class="linkToolProjetCreation-al">
					<i class="fas fa-pencil-alt childFlex iconToolEditPC-al" id="btnEditProjetCreation-al"></i>
				</a>
				<a href="@Url.Action("Del_MsgModalCreationProjectAd", "Ad_CreationProject" , null)" rel="modal:open" class="linkToolProjetCreation-al">
					<i class="fas fa-trash childFlex iconToolEditPC-al" id="btnRemoveProjetCreation-al"></i>
				</a>
			</div>
		}
		<a id="projetCreationPVLink-1" href='@Url.Action("Read_ModalCreationProjectAd","Ad_CreationProject", new { @idModal = 1})' rel="modal:open" class="col-sm-11 col-xs-12 childFlex noLink">
			<div id="div1-1PC">
				<div id="div2PC" class="fontFamilyNote">
					<div id="div1ProfilPC" class="col-sm-4">
						<div id="divIdentitePC" class="col-sm-12 col-xs-6">
							<div id="divPhotoProfilPC" class="col-sm-5 col-xs-5">
								<div id="photoProfilPC"></div>
							</div>
							<div id="div0DecriptionIdentitePC">
								<div id="div1DecriptionIdentitePC">
									<div id="div2DecriptionIdentitePC">
										<p>Matias.</p>
										<p>indépendent</p>
										<p>22 ans</p>
									</div>
								</div>
							</div>
						</div>
						<div id="div1PersonnalitePC" class="col-sm-12 col-xs-6">
							<div id="div2PersonnalitePC" class="div2PersonnaliteColorPC">
								<p id="personnalityProfilPC">Etudiant dans les soins énergétiques. J'ai un tempérament calme et à la fois très sociable. J'aime m'amuser et partager des bons moments entres amis.</p>
							</div>
						</div>
						<div id="div1InscriptionPC" class="col-sm-12 col-xs-12">
							<div id="div11InscriptionPC" class="col-sm-12 col-xs-5">
								<div id="div2InscriptionPC">
									<div>Membre depuis hier</div>
								</div>
							</div>
						</div>
					</div>
					<div id="div1DescriptionPC" class="col-sm-8">
						<h3>Auto-construction d'un éco-habitat pour y vivre en eco-colocation.</h3>
						<div id="div2DescriptionPC">
							<p>
								J'ai dernièrement acheté un terrain, je souhaiterai trouver des personnes qui veulent se lancer
								dans l'aventure de vivre dans un Habitat insolite à 5 colocataires. L'objectif est qu'on puisse tous
								ensemble être acheteur du terrain et des matériaux pour auto-construire. Je recherche donc 4
								autres personnes qui s'investirai dans le projet d'auto-construction. Au niveau de la
								convivialité commune j'aimerai qu'on puisse tous ensemble partager des repas et pourquoi pas
								des soirées ensemble. Au niveau de la gestion des taches et des ressoruces financières je n'ai
								pas encore réflechi à l'organisation mais je pense qu'il sera important d'y réflechir tous ensemble.
								Concernant les pratiques écologiques il y aura un grand potager et puis je souhaiterai
								qu'on tendent vers du zéro déchet.
							</p>
						</div>
					</div>
				</div>
			</div>
		</a>
	</div>
	<div class="flex childFlex divHighterProjetCreationPVLink">
		@if (User.Identity.IsAuthenticated & ViewBag.researchType == "offering")
		{
			<div class="divToolEditProjetCreation-al">
				<i class="fas fa-pencil-alt childFlex iconToolEditPC-al" id="btnEditProjetCreation-al"></i>
				<i class="fas fa-trash childFlex iconToolEditPC-al" id="btnRemoveProjetCreation-al"></i>
			</div>
		}
		<a id="projetCreationPVLink-2" href='@Url.Action("Read_ModalCreationProjectAd","Ad_CreationProject", new { @idModal = 2})' rel="modal:open" class="col-sm-11 col-xs-12 childFlex  noLink">
			<div id="div1-1PC">
				<div id="div2PC" class="fontFamilyNote">
					<div id="div1ProfilPC" class="col-sm-4">
						<div id="divIdentitePC" class="col-sm-12 col-xs-6">
							<div id="divPhotoProfilPC" class="col-sm-5 col-xs-5">
								<div id="photoProfilPC"></div>
							</div>
							<div id="div0DecriptionIdentitePC">
								<div id="div1DecriptionIdentitePC">
									<div id="div2DecriptionIdentitePC">
										<p>Matias.</p>
										<p>indépendent</p>
										<p>22 ans</p>
									</div>
								</div>
							</div>
						</div>
						<div id="div1PersonnalitePC" class="col-sm-12 col-xs-6">
							<div id="div2PersonnalitePC" class="div2PersonnaliteColorPC">
								<p id="personnalityProfilPC">Etudiant dans les soins énergétiques. J'ai un tempérament calme et à la fois très sociable. J'aime m'amuser et partager des bons moments entres amis.</p>
							</div>
						</div>
						<div id="div1InscriptionPC" class="col-sm-12 col-xs-12">
							<div id="div11InscriptionPC" class="col-sm-12 col-xs-5">
								<div id="div2InscriptionPC">
									<div>Membre depuis hier</div>
								</div>
							</div>
						</div>
					</div>
					<div id="div1DescriptionPC" class="col-sm-8">
						<h3>Auto-construction d'un éco-habitat pour y vivre en eco-colocation.</h3>
						<div id="div2DescriptionPC">
							<p>
								J'ai dernièrement acheté un terrain, je souhaiterai trouver des personnes qui veulent se lancer
								dans l'aventure de vivre dans un Habitat insolite à 5 colocataires. L'objectif est qu'on puisse tous
								ensemble être acheteur du terrain et des matériaux pour auto-construire. Je recherche donc 4
								autres personnes qui s'investirai dans le projet d'auto-construction. Au niveau de la
								convivialité commune j'aimerai qu'on puisse tous ensemble partager des repas et pourquoi pas
								des soirées ensemble. Au niveau de la gestion des taches et des ressoruces financières je n'ai
								pas encore réflechi à l'organisation mais je pense qu'il sera important d'y réflechir tous ensemble.
								Concernant les pratiques écologiques il y aura un grand potager et puis je souhaiterai
								qu'on tendent vers du zéro déchet.
							</p>
						</div>
					</div>
				</div>
			</div>
		</a>
	</div>
	<div id="divOthersAnnounces-pcpv" class="overflow"></div>
	<div class="flex">
		<div class="btnGreen childFlex" id="btnOtherAnnonceLocation-pcpv" onclick="showOthersProjetCreationAnnounces()">
			<p id="txtShowNewEvent-alpv">Voir plus d'annonces</p>
			<div class="flex"><i class="fas fa-sort-down childFlex" id="iconShowNewEvent-alpv"></i></div>
		</div>
	</div>
</div>

<script language="javascript">
	$(document).ready(function () {
		lineMaxToShow("#personnalityProfilPC");

		copyDivToOtherElement("#projetCreationAnnounce", "#lstCreationProjectAd-cpv")
	});
</script>

Eco-Colocation/Views/Ad_CreationProject/Del_MsgModalCreationProjectAd.cshtml
@{
	ViewBag.Title = "Del_MsgModalCreationProjectAd";
}

<div class="underModal col-sm-12 col-xs-12">
	<div id="del_MsgModalEcoRoommateExisting" class="reelModal">
		<h2 class="title centerText">Suppression de votre projet de création</h2>
		<p id="titleTop-mder">Voulez êtes sur le point de supprimer votre annonce "TITRE DE L'ANNONCE". Confirmez-vous l'opération ?</p>
		<div class="flex">
			<div style="margin-left:auto;flex-wrap: wrap;display: flex;">
				<div class="divBtn-mder">
					<a href="#close-modal" rel="modal:close" class="closeModal" id="btnCancelInfo-mder">Annuler</a>
				</div>
				<div class="divBtn-mder">
					<a id="btnDeleteInfo-mder" href="@Url.Action("DeleteProjectCreation", "Ad_CreationProject", null)">Oui, je confirme</a>
				</div>
			</div>
		</div>
	</div>
</div>

Eco-Colocation/Views/Ad_CreationProject/Read_ModalCreationProjectAd.cshtml
@{
	ViewBag.Title = "Read_ModalCreationProjectAd";
}

<div class="underModal col-sm-12 col-xs-12">
	<div id="modalCreationProjet-SearchColoc" class="reelModal">
		<div id="divMessage-ml">
			<img onclick="displayPVMessage()" src="https://img.icons8.com/material-outlined/40/000000/circled-chevron-left.png">
			<div class="col-sm-6 col-xs-12" style="padding:0">
				@Html.Partial("~/Views/ContactUs/PartialViewMessage.cshtml")
			</div>
		</div>
		<div id="divPhoto-ml">
			<div id="div-photos-mpc" class="col-sm-6 col-xs-12">
				<div class="photo-mpc mySlides" style="background: url(https://d2v8xh2t491lqq.cloudfront.net/photos/listings/b/5/d/e/d/b5dedf6aedec903908e57c2b0877ac34cacf3227-biggest.jpg) 50% 50% no-repeat;"></div>
				<div class="photo-mpc mySlides" style="background: url(https://www.century21-ci-etampes.com/imagesBien/202/3238/c21_202_3238_13298_1_BC5D7902-0D5B-4309-B442-1150B2E3CDE2.jpg) 50% 50% no-repeat;"></div>
				<div class="photo-mpc mySlides" style="background: url(https://tel.img.pmdstatic.net/fit/http.3A.2F.2Fwww.2Eprogramme.2Etv.2Fupload.2Fepgs.2F2018.2F01.2Ftiny-house-mini-maison-a-emporter_123388556_2.2Ejpg/355x272/quality/80/tiny-house-mini-maison-a-emporter.jpg) 50% 50% no-repeat;"></div>
				<div id="d1-btnphoto-mpc">
					<div id="d1-2-btnphoto-mpc" onclick="plusDivs(-1)">
						<img src="/Content/Images/Icons/arrow-left.png">
					</div>
				</div>
				<div id="d2-btnphoto-mpc">
					<div id="d2-1-btnphoto-mpc" onclick="plusDivs(+1)">
						<img src="/Content/Images/Icons/arrow-right.png">
					</div>
				</div>
			</div>
		</div>
		<div id="div-description-mpc" class="col-sm-6 col-xs-12 fontFamilyNote">
			<div id="d1-description-mpc">
				<div id="d1-description-mpc" style="display: flex;">
					<div style="margin-left: auto;margin-right: auto;display: flex;">
						<div id="d1-2-description-mpc" class="col-sm-5 col-xs-5" style="margin-left: auto;margin-right:auto">
							<div id="d1-2-1-description-mpc" style="background: url(/Content/Images/Personnes/Profil1.jpg) 50% 50% no-repeat;"></div>
						</div>
						<div id="d1-3-description-mpc" class="col-sm-7 col-xs-7" style="margin-left: auto;margin-right: auto;">
							<h4>Matias</h4>
							<p>22 ans, Indépendent</p>
							<p id="p-d1-3-description-mpc">Posté il y a 3 jours</p>
						</div>
					</div>
				</div>
				<div id="div1PersonnalitePC" class="col-sm-12">
					<div id="div2PersonnalitePC" style="width: initial;">
						<p style="text-align: center;">Etudiant dans les soins énergétiques. J'ai un tempérament calme et à la fois très sociable.</p>
					</div>
				</div>
			</div>
			<div id="d3-description-mpc">
				@if (User.Identity.IsAuthenticated)
				{
					<div class="d3-1-description-mpc btnGreen" onclick="displayPhoneNumber('#numberPhone-mpc'/*Passer id client*/)">
						<i class="fas fa-phone imgBtnContact-mpc"></i>
						<span id="libelleTelephone-mpc">Afficher le numéro</span>
						<span id="numberPhone-mpc"></span>
					</div>
				}
				else
				{
					<a class="d3-1-description-mpc btnGreen" href="@Url.Action("ModalAccount", "Account", null)" rel="modal:open">
						<i class="fas fa-phone imgBtnContact-mpc"></i>
						<span id="libelleTelephone-mpc">Afficher le numéro</span>
						<span id="numberPhone-mpc"></span>
					</a>
				}
				@if (User.Identity.IsAuthenticated)
				{
					<div id="d3-2-description-mpc" onclick="displayPVMessage();$('#modalLocation').scrollTop(0);" class="btnGreen">
						<i class="far fa-envelope imgBtnContact-mpc"></i>Envoyer un message
					</div>
				}
				else
				{
					<a id="d3-2-description-mpc" href="@Url.Action("ModalAccount", "Account", null)" rel="modal:open" class="btnGreen">
						<i class="far fa-envelope imgBtnContact-mpc"></i>Envoyer un message
					</a>
				}
			</div>
			<div id="d4-description-mpc">
				<div class="flex">
					<h4 class="centerText childFlex" id="instroductionTitleAnnonce-mpc">Auto-construction d'un éco-habitat pour y vivre en eco-colocation. </h4>
				</div>
				<p id="textAnnonce-mpc">
					Bonjour, j'ai dernièrement acheté un terrain,
					je souhaiterai trouver des personnes qui veulent se lancer dans l'aventure de vivre dans un Habitat insolite à
					5 colocataires. L'objectif est qu'on puisse tous ensemble être acheteur du terrain et des matériaux pour
					auto-construire. Je recherche donc 4 autres personnes qui s'investirai dans le projet d'auto-construction.
					Au niveau de la convivialité commune j'aimerai qu'on puisse tous ensemble partager des repas et pourquoi pas
					des soirées ensemble. Au niveau de la gestion des taches et des ressoruces financières je n'ai pas encore
					réflechi à l'organisation mais je pense qu'il sera important d'y réflechir tous ensemble. Concernant les
					pratiques écologiques il y aura un grand potager et puis je souhaiterai qu'on tendent vers du
					zéro déchet.
				</p>
			</div>
			<div id="d5-description-mpc">

				<table class="table table-striped">
					<thead>
						<tr>
							<th scope="col" colspan="2">Lieu(x) concerné(s)</th>
						</tr>
					</thead>
					<tbody>
						<tr>
							<td>Rennes 35, Ille-et-Vilaine, Bretagne</td>

						</tr>
						<tr>
							<td>Nouvoitou 35, Ille-et-Vilaine, Bretagne</td>

						</tr>
						<tr>
							<td>Vern-sur-Seiche 35, Ille-et-Vilaine, Bretagne</td>

						</tr>
					</tbody>
				</table>
				<table class="table table-striped">
					<thead>
						<tr>
							<th scope="col" colspan="2">TERRAIN</th>
						</tr>
					</thead>
					<tbody>
						<tr>
							<td>Engagement</td>
							<td>Achat</td>
						</tr>
						<tr>
							<td>Superficie maximum</td>
							<td>2 ha² ou plus</td>
						</tr>
						<tr>
							<td>Cout de l'achat maximum</td>
							<td>30 000 euros</td>
						</tr>
					</tbody>
				</table>
				<table class="table table-striped">
					<thead>
						<tr>
							<th scope="col" colspan="2">LOGEMENT</th>
						</tr>
					</thead>
					<tbody>
						<tr>
							<td>Engagement</td>
							<td>Création</td>
						</tr>
						<tr>
							<td>Type d'habitat</td>
							<td>Habitat insolite</td>
						</tr>
						<tr>
							<td>Implantation</td>
							<td>Campagne</td>
						</tr>
						<tr>
							<td>Superficie maximum</td>
							<td>~ 400 m²</td>
						</tr>
						@* Selon l'engagement *@
						<tr>
							<td>Cout de construction maximum</td>
							<td>~ 15 000 euros</td>
						</tr>
						<tr>
							<td>Cout de l'achat maximum</td>
							<td>Aucun</td>
						</tr>
						<tr>
							<td>Loyer / personne maximum</td>
							<td>Aucun</td>
						</tr>
					</tbody>
				</table>
				<table class="table table-striped">
					<thead>
						<tr>
							<th scope="col" colspan="2">COLOCATION</th>
						</tr>
					</thead>
					<tbody>
						<tr>
							<td>Nombre de personne au totale</td>
							<td>5</td>
						</tr>
						<tr>
							<td>Personnes recherchées pour partager l'achat du terrain</td>
							<td>4</td>
						</tr>

						<tr>
							<td>Personnes recherchées pour partager l'achat du logement</td>
							<td>4</td>
						</tr>
						<tr>
							<td>Personnes recherchées pour louer le logement</td>
							<td>0</td>
						</tr>
					</tbody>
				</table>
				<table class="table table-striped">
					<thead>
						<tr>
							<th scope="col" colspan="2">ACCESSIBILITES</th>
						</tr>
					</thead>
					<tbody>
						<tr>
							<td>Transport en communs</td>
							<td>Oui</td>
						</tr>
						<tr>
							<td>Info supplémentaire</td>
							<td>Les transports en communs sont accessibles à quelque minutes en vélo.</td>
						</tr>
					</tbody>
				</table>
				<table class="table table-striped">
					<thead>
						<tr>
							<th scope="col" colspan="2">TOLERANCES</th>
						</tr>
					</thead>
					<tbody>
						<tr>
							<td>Consommateur d'alcool</td>
							<td>Oui</td>
						</tr>
						<tr>
							<td>Fumeur</td>
							<td>Oui</td>
						</tr>
						<tr>
							<td>Animaux</td>
							<td>Oui</td>
						</tr>
						<tr>
							<td>Info supplémentaire</td>
							<td>Ne pas fumer à l'interieur</td>
						</tr>
					</tbody>
				</table>
				<table class="table table-striped">
					<thead>
						<tr>
							<th scope="col" colspan="2">ANNONCE</th>
						</tr>
					</thead>
					<tbody>
						<tr>
							<td>Date de publication</td>
							<td>16/02/2019 à 20h00</td>
						</tr>
					</tbody>
				</table>
			</div>
		</div>
	</div>
	<div class="divCloseModal">
		<a href="#close-modal" rel="modal:close"><i class="fas fa-times close-modal"></i></a>
	</div>
</div>

<script language="javascript">
	$(document).ready(function () {
		window.history.replaceState('data to be passed', 'Title of the page',
			'/Modal/Read_ModalCreationProjectAd/?targetCity=' + "@ViewData["targetCity"]" + "&idModal=" + @ViewData["IdModal"]  + "&urlCurrentPage=" + $('#urlCurrentPage').val() + "&researchType=" + $("#researchType").val());
	});
</script>