Eco-Colocation/Controllers/Ad_RentalController.cs
using Eco_Colocation.ViewModel;
using System.Web.Mvc;

namespace Eco_Colocation.Controllers
{
	public class Ad_RentalController : Controller
	{
		// GET: Ad_Rental
		public ActionResult Index()
		{
			return View();
		}

		public ActionResult Read_ModalRentalAd(string idModal)
		{
			ViewData["targetCity"] = "Rennes";
			ViewData["IdModal"] = idModal;

			return PartialView();
		}

		public ActionResult AddUpd_ModalRentalAd(string operation)
		{
			if (operation != null)
			{
				ViewData["operation"] = operation;
			}

			ViewData["targetCity"] = "Rennes";

			AllViewModel AllViewModel = new AllViewModel();

			return PartialView(AllViewModel);
		}

		public ActionResult Del_MsgModalRentalAd()
		{ 
			return PartialView();
		}

		public ActionResult DeleteRentalAd()
		{
			return RedirectToAction("CommonAd", "EcoRoommateHome", new { currentTab = "AnnonceLocation", researchType = "offering" });
		}		
	}
}

Eco-Colocation/Views/Ad_Rental/Del_MsgModalRentalAd.cshtml
@{
	ViewBag.Title = "Del_MsgModal";
}

<div class="underModal col-sm-12 col-xs-12">
	<div id="Del_MsgModalEcoRoommateExisting" class="reelModal">
		<h2 class="title centerText">Suppression de votre location</h2>
		<p id="titleTop-mder">Voulez êtes sur le point de supprimer votre annonce "TITRE DE L'ANNONCE". Confirmez-vous l'opération ?</p>
		<div class="flex">
			<div style="margin-left:auto;flex-wrap: wrap;display: flex;">
				<div class="divBtn-mder">
					<a href="#close-modal" rel="modal:close" class="closeModal" id="btnCancelInfo-mder">Annuler</a>
				</div>
				<div class="divBtn-mder">
					<a id="btnDeleteInfo-mder" href="@Url.Action("DeleteRentalAd", "Ad_Rental", null)">Oui, je confirme</a>
				</div>
			</div>
		</div>
	</div>
</div>

Eco-Colocation/Views/Ad_Rental/Read_ModalRentalAd.cshtml
@{
	ViewBag.Title = "Read_ModalRentalAd";
}

<div class="underModal col-sm-12 col-xs-12">
	<div id="modalLocation" class="reelModal col-sm-8 col-xs-12">
		<div id="divMessage-ml">
			<img onclick="displayPVMessage()" src="https://img.icons8.com/material-outlined/40/000000/circled-chevron-left.png">
			<div class="col-sm-6 col-xs-12" style="padding:0">
				@Html.Partial("~/Views/ContactUs/PartialViewMessage.cshtml")
			</div>
		</div>
		<div id="divPhoto-ml">
			<div id="div-photos-mpc" class="col-sm-6 col-xs-12">
				<div class="photo-mpc mySlides" style="background: url(https://lcdcfrance-prod.s3.amazonaws.com/pictures/1fcfb11b21b7a9b1246992c16d340f7c_medium.jpg) 50% 50% no-repeat;"></div>
				<div class="photo-mpc mySlides" style="background: url(https://lcdcfrance-prod.s3.amazonaws.com/pictures/419b0732bf01daa64a17797c482fc47a_medium.jpg) 50% 50% no-repeat;"></div>
				<div class="photo-mpc mySlides" style="background: url(https://lcdcfrance-prod.s3.amazonaws.com/pictures/69617d56d55af3985e8ab7bb6ae947d5_medium.jpg) 50% 50% no-repeat;"></div>
				<div id="d1-btnphoto-mpc">
					<div id="d1-2-btnphoto-mpc" onclick="plusDivs(-1)">
						<img src="/Content/Images/Icons/arrow-left.png">
					</div>
				</div>
				<div id="d2-btnphoto-mpc">
					<div id="d2-1-btnphoto-mpc" onclick="plusDivs(+1)">
						<img src="/Content/Images/Icons/arrow-right.png">
					</div>
				</div>
			</div>
		</div>
		<div id="div-description-mpc" class="col-sm-6 col-xs-12 fontFamilyNote">
			<div id="divOngletAnnonce-ml" class="flex">
				<div class="ongletAnnonce-ml" id="annonceOnglet-ml" data-id="annonceInfo-ml" data-selected="true">Annonce</div>
				<div class="ongletAnnonce-ml" id="localisationOnglet-ml" data-id="localisationMarkerOnMap-ml" data-showmap="true" data-mapisinit="false">Localisation</div>
			</div>
			<div class="viewFromOnglet-ml" id="localisationMarkerOnMap-ml"></div>
			<div class="viewFromOnglet-ml" id="annonceInfo-ml">
				<div id="d1-description-mpc">
					<div id="d1-1-description-mpc" class="col-sm-4 col-xs-4">
						<div id="d1-1-1-description-mpc">
							<h2>390€</h2>
							<h4>par mois</h4>
						</div>
					</div>
					<div id="d1-2-description-mpc" class="col-sm-3 col-xs-3">
						<div id="d1-2-1-description-mpc" style="background: url(https://lcdcfrance-prod.s3.amazonaws.com/profile_pictures/47aa8a5c7db1808139e223af6a4ab1e0_medium.jpg) 50% 50% no-repeat;"></div>
					</div>
					<div id="d1-3-description-mpc" class="col-sm-5 col-xs-5">
						<h4>Clémentine</h4>
						<p>25 ans, Salariée</p>
						<p id="p-d1-3-description-mpc">Posté il y a 3 jours</p>
					</div>
				</div>
				<div class="d2-description-mpc fontFamilyNote">
					<div class="d2-1-description-mpc col-sm-3 col-xs-3">
						<div class="d2-1-1-description-mpc">
							<div class="d2-1-1-1-description-mpc">
								<img src="https://img.icons8.com/ios/50/000000/building.png">
							</div>
							<p>Maison de 120 m²</p>
						</div>
					</div>
					<div class="d2-1-description-mpc col-sm-3 col-xs-3">
						<div class="d2-1-1-description-mpc">
							<div class="d2-1-1-1-description-mpc">
								<img src="https://img.icons8.com/ios/50/000000/resize-four-directions.png">
							</div>
							<p>Allée de la bome marudière, Rennes</p>
						</div>
					</div>
					<div class="d2-1-description-mpc col-sm-3 col-xs-3">
						<div class="d2-1-1-description-mpc">
							<div class="d2-1-1-1-description-mpc">
								<img src="https://img.icons8.com/ios/50/000000/conference-call.png">
							</div>
							<p id="p1-d2-1-description-mpc">2 place(s) sur 5</p>
							<p id="p2-d2-1-description-mpc">restantes</p>
						</div>
					</div>
					<div class="d2-1-description-mpc col-sm-3 col-xs-3">
						<div class="d2-1-1-description-mpc">
							<div class="d2-1-1-1-description-mpc">
								<img src="https://img.icons8.com/wired/64/000000/event-declined.png">
							</div>
							<p id="p1-d2-1-description-mpc">01/08/2020</p>
							<p id="p2-d2-1-description-mpc">(Disponibilité)</p>
						</div>
					</div>
				</div>
				<div id="d3-description-mpc">
					@if (User.Identity.IsAuthenticated)
					{
						<div class="d3-1-description-mpc btnGreen" onclick="displayPhoneNumber('#numberPhone-ml')">
							<i class="fas fa-phone imgBtnContact-mpc"></i>
							<span id="libelleTelephone-mpc">Afficher le numéro</span>
							<span id="numberPhone-ml"></span>
						</div>
					}
					else
					{
						<a class="d3-1-description-mpc btnGreen" href="@Url.Action("ModalAccount", "Account", null)" rel="modal:open">
							<i class="fas fa-phone imgBtnContact-mpc"></i>
							<span id="libelleTelephone-mpc">Afficher le numéro</span>
							<span id="numberPhone-ml"></span>
						</a>
					}

					@if (User.Identity.IsAuthenticated)
					{
						<div id="d3-2-description-mpc" onclick="displayPVMessage();$('#modalLocation').scrollTop(0);" class="btnGreen">
							<i class="far fa-envelope imgBtnContact-mpc"></i>Envoyer un message
						</div>
					}
					else
					{
						<a id="d3-2-description-mpc" href="@Url.Action("ModalAccount", "Account", null)" rel="modal:open" class="btnGreen">
							<i class="far fa-envelope imgBtnContact-mpc"></i>Envoyer un message
						</a>
					}
				</div>
				<div id="d4-description-mpc">
					<div class="flex">
						<h4 class="childFlex centerText" id="instroductionTitleAnnonce-mpc">Deux chambre se libère de notre maison.</h4>
					</div>
					<p id="textAnnonce-mpc">
						Nous recherchons 2 hommes pour amener une mixité dans la colocation et qui seraient interressés pour co-habiter avec nous et participer à ces démarches écologiques. Nous sommes 3 jeunes femmes entre 22 et 26 ans. Nous vivons dans une maison dans la campagne prêt de la mer. Deux de nos colocataires partent étudier dans hors Toulouse, deux nouvelles places sont alors disponibles. Nous respectons les tri des dechets, essayons d'être proche du 0 déchets et nous cultivons notre jardin bio. Et enfin nous ne mangeons pas de viande.
					</p>
				</div>
				<div id="d5-description-mpc">
					<table class="table table-striped">
						<thead>
							<tr>
								<th scope="col" colspan="2">CHAMBRE 1</th>
							</tr>
						</thead>
						<tbody>
							<tr>
								<td>Loyer (hors charges)</td>
								<td>320 €</td>
							</tr>
							<tr>
								<td>Charges</td>
								<td>
									50 €
									<i class="fas fa-question-circle iconQuestionCharge-ml" id="iconQuestionCharge1"
									   onmouseover="showPopUpInfo('#iconQuestionCharge1', '#divInfoSupCharge1')"></i>
									<div class="divInfoSupCharge-ml" id="divInfoSupCharge1">
										50 euros pour l'eau, électricité et chauffage.
									</div>
								</td>
							</tr>
							<tr>
								<td>Caution</td>
								<td>250 €</td>
							</tr>
							<tr>
								<td>Superficie</td>
								<td>18 m²</td>
							</tr>
							<tr>
								<td>Meublée</td>
								<td>Oui</td>
							</tr>
							<tr>
								<td>Disponibilité</td>
								<td>01/08/2020</td>
							</tr>
							<tr>
								<td>Fin de la disponibilité</td>
								<td>01/09/2020</td>
							</tr>
						</tbody>
					</table>
					<table class="table table-striped">
						<thead>
							<tr>
								<th scope="col" colspan="2">CHAMBRE 2</th>
							</tr>
						</thead>
						<tbody>
							<tr>
								<td>Loyer (hors charges)</td>
								<td>320 €</td>
							</tr>
							<tr>
								<td>Charges</td>
								<td>
									50 €
									<i class="fas fa-question-circle iconQuestionCharge-ml" id="iconQuestionCharge2"
									   onmouseover="showPopUpInfo('#iconQuestionCharge2', '#divInfoSupCharge2')"></i>
									<div class="divInfoSupCharge-ml" id="divInfoSupCharge2">
										50 euros pour l'eau, électricité et chauffage.
									</div>
								</td>
							</tr>
							<tr>
								<td>Caution</td>
								<td>200 €</td>
							</tr>
							<tr>
								<td>Superficie</td>
								<td>15 m²</td>
							</tr>
							<tr>
								<td>Meublée</td>
								<td>Oui</td>
							</tr>
							<tr>
								<td>Disponibilité</td>
								<td>25/03/2019</td>
							</tr>
						</tbody>
					</table>
					<table class="table table-striped">
						<thead>
							<tr>
								<th scope="col" colspan="2">LOGEMENT</th>
							</tr>
						</thead>
						<tbody>
							<tr>
								<td>Type</td>
								<td>Maison</td>
							</tr>
							<tr>
								<td>Implantation</td>
								<td>Campagne</td>
							</tr>
							<tr>
								<td>Superficie du logement</td>
								<td>120 m²</td>
							</tr>
							<tr>
								<td>Superficie du terrain</td>
								<td>200 m²</td>
							</tr>
							<tr>
								<td>localisation</td>
								<td>Allée de la bome marudière, Rennes</td>
							</tr>
							<tr>
								<td>Nombre de pièce</td>
								<td>5</td>
							</tr>
							<tr>
								<td>Habitants restants</td>
								<td>3</td>
							</tr>
							<tr>
								<td>Colocataires recherchés</td>
								<td>2</td>
							</tr>
						</tbody>
					</table>
					<table class="table table-striped">
						<thead>
							<tr>
								<th scope="col" colspan="2">ACCESSIBILITES</th>
							</tr>
						</thead>
						<tbody>
							<tr>
								<td>Accessibilité handicapé</td>
								<td>Oui</td>
							</tr>
							<tr>
								<td>Transport en communs</td>
								<td>Oui</td>
							</tr>
							<tr>
								<td>Info supplémentaire</td>
								<td>J'aimerai que les transports en communs soient au moins accessibles à quelque minutes en vélo.</td>
							</tr>
						</tbody>
					</table>
					<table class="table table-striped">
						<thead>
							<tr>
								<th scope="col" colspan="2">TOLERENCES</th>
							</tr>
						</thead>
						<tbody>
							<tr>
								<td>Consommateur d'alcool</td>
								<td>Oui</td>
							</tr>
							<tr>
								<td>Fumeur</td>
								<td>Oui</td>
							</tr>
							<tr>
								<td>Animaux</td>
								<td>Oui</td>
							</tr>
							<tr>
								<td>Info supplémentaire</td>
								<td>Peut fumer uniquement sur le balcon</td>
							</tr>
						</tbody>
					</table>
					<table class="table table-striped">
						<thead>
							<tr>
								<th scope="col" colspan="2">ANNONCE</th>
							</tr>
						</thead>
						<tbody>
							<tr>
								<td>Date de publication</td>
								<td>16/02/2019 à 20h00</td>
							</tr>
						</tbody>
					</table>
				</div>
			</div>
		</div>
	</div>
	<div class="divCloseModal">
		<a href="#close-modal" rel="modal:close"><i class="fas fa-times close-modal"></i></a>
	</div>
</div>
<script language="text/javascript">
	$(document).ready(function () {
		window.history.replaceState('data to be passed', 'Title of the page',
			'/Modal/Read_ModalRentalAd/?targetCity=' + "@ViewData["targetCity"]" + "&idModal=" + @ViewData["IdModal"] + "&urlCurrentPage=" + $('#urlCurrentPage').val());

		$(".ongletAnnonce-ml").on("click", function (e) { changeOngletInModalLocation(e.target) })
	});
</script>

Eco-Colocation/Views/Ad_Rental/Read_PopupMarkerRental.cshtml
@{
	ViewBag.Title = "Read_PopupMarkerRental";
}

<div class="onHoverMarker" id="onHoverMarker1">
	<div id="divPrixAnnonce">
		<div id="prixAnnonce">340€<span id="rentCosts">/mois</span></div>
	</div>
	<div id="markerPhoto" class="col-md-5 col-xs-5">
		<img class="img-responsive col-xs-12" src="https://lcdcfrance-prod.s3.amazonaws.com/pictures/5971704b03891a82ae95f895a7700705_small.jpg" style="padding: 0;">
	</div>
	<div id="description" class="col-md-7 col-xs-7">
		<p class="nameColoc-al">Maison de 5 collocataires</p>
		<p class="fontFamilyNote centerText underTitlePopup-al">1 chambre disponible dès le 11/12/2019</p>
		<p class="descriptionHabitat-al fontFamilyNote">Nous recherchons 2 hommes pour amener une mixité...</p>
	</div>
	<div id="divLinkDetailEvent-erevom" class="col-xs-12">
		<a id="annonceLocationPVLink-1" class="linkDetailEvent-al" rel="modal:open" href="@Url.Action("Read_ModalRentalAd","Ad_Rental", new { @idModal = "1" })">
			<i id="iconDetailEvent-erevom" class="fas fa-angle-double-right"></i>
			<p class="fontFamilyNote autoMargin">En savoir plus</p>
		</a>
	</div>
</div>

<div class="onHoverMarker" id="onHoverMarker2">
	<div id="divPrixAnnonce">
		<div id="prixAnnonce">340€<span id="rentCosts">/mois</span></div>
	</div>
	<div id="markerPhoto" class="col-md-5 col-xs-5">
		<img class="img-responsive col-xs-12" src="https://lcdcfrance-prod.s3.amazonaws.com/pictures/5971704b03891a82ae95f895a7700705_small.jpg" style="padding: 0;">
	</div>
	<div id="description" class="col-md-7 col-xs-7">
		<p class="nameColoc-al">Maison de 5 collocataires</p>
		<p class="fontFamilyNote centerText underTitlePopup-al">2 chambres disponibles dès le 01/08/2020</p>
		<p class="descriptionHabitat-al fontFamilyNote">Nous recherchons 2 hommes pour amener une mixité...</p>
	</div>
	<div id="divLinkDetailEvent-erevom" class="col-xs-12">
		<a id="annonceLocationPVLink-2" class="linkDetailEvent-al" rel="modal:open" href="@Url.Action("Read_ModalRentalAd","Ad_Rental", new { @idModal = "2" })">
			<i id="iconDetailEvent-erevom" class="fas fa-angle-double-right"></i>
			<p class="fontFamilyNote autoMargin">En savoir plus</p>
		</a>
	</div>
</div>

Eco-Colocation/Views/Ad_Rental/RentalView.cshtml
@{
	ViewBag.Title = "RentalView";
	ViewBag.researchType = ViewData["researchType"];
}

@if (ViewBag.researchType == "offering")
{
	<div id="div1-annonceLocation" class="col-xs-12">
		<div id="div1-1-al" class="col-sm-12">
			<div id="div1-2-al">
				<a href="@Url.Action("AddUpd_ModalRentalAd", "Ad_Rental", null)" rel="modal:open">
					<div id="btnCreer-al" class="createAnnounceLocationLink-al">Creer une annonce de location</div>
				</a>
			</div>
		</div>

		<div class="col-sm-12" style="display: flex;padding:0">
			<div id="divDivBlocAnnonce" class="col-md-9 col-sm-12">
				@if (User.Identity.IsAuthenticated)
				{
					<div id="lstRentalAd-rad"></div>
				}
			</div>
		</div>
	</div>
}
else if (ViewBag.researchType == "searching")
{
	@Html.Partial("~/Views/Ad_Rental/Read_PopupMarkerRental.cshtml")
	@Html.Partial("~/Views/Ad_Rental/Read_PopupMarkerPartner.cshtml")

	<div class="col-md-6 col-sm-12" id="globalDivMapSearchColoc">
		<div id="divMultiPlaceToSearch-al" class="flex">
			<div id="underDivMultiPlaceToSearch-al" class="flex">
				<label for="inpMultiPlace-al"><i class="fas fa-map-marker-alt" id="iMarkerMultiPlace-al"></i></label>
				<input type="text" placeholder="Rajouter des communes" id="inpMultiPlace-al" oninput="addr_searchCity(this);">
				@*<input type="text" placeholder="Rajouter des départements" id="inpMultiPlace-al" oninput="addr_searchDepartement(this);">*@
			</div>
			<div class="flex overflow" id="place-al">
				<div id="place1" class="divPlace"><p class="placeName">Rennes 35, Ille-et-Vilaine, Bretagne</p><div class="crossPlace"><i onclick="deletePlace(place1, 'al')" class="fas fa-times crossplace"></i></div></div>
			</div>
		</div>
		<div id="divMapSearchColoc"><div id="mapSearchColoc"></div></div>
	</div>
	@*****@

	<div id="divDivBlocAnnonce" class="col-md-6 col-sm-12">
		<div id="divDivBlocAnnonce2" class="col-xs-12">
			@Html.Partial("~/Views/Ad_Rental/FiltersRentalAd.cshtml")
		</div>
		<div id="lstRentalAd-rad"></div>
	</div>
}

<div id="divContenerBlocAnnonce" class="flex">
	<div id="divBlocAnnonce" class="col-xs-12">
		<div id="annonce1-alpv" class="divBlocAnnonce1-ereom">
			<div id="divBlocAnnonce2" class="col-sm-12 col-xs-12">
				@if (User.Identity.IsAuthenticated && ViewBag.researchType == "offering")
				{
					<div class="divToolEditAnnonceLocation-alpv">
						<a href="@Url.Action("AddUpd_ModalRentalAd", "Ad_Rental", new { @operation = "Update"})" rel="modal:open" class="linkToolProjetCreation-al">
							<i class="fas fa-pencil-alt childFlex iconToolEditPC-al" id="btnEditProjetCreation-al"></i>
						</a>
						<a href="@Url.Action("Del_MsgModalRentalAd", "Ad_Rental", null)" rel="modal:open" class="linkToolProjetCreation-al">
							<i class="fas fa-trash childFlex iconToolEditPC-al" id="btnRemoveProjetCreation-al"></i>
						</a>
					</div>
				}
				<a id="annonceLocationPVLink-1" href="@Url.Action("Read_ModalRentalAd","Ad_Rental", new { @idModal = "1" })" rel="modal:open">
					<div id="underAnnonce2-alpv" class="col-md-12 col-sm-12 divAnnonceColoc">
						<div id="div2AnnonceColoc" class="col-md-12 col-sm-12 col-xs-12">
							<input id="valueGps10" name="valueGps10" type="hidden" value="46.89, 2.67">
							<div id="divPrixAnnonce">
								<div id="prixAnnonce">340€<span id="rentCosts">/mois</span></div>
							</div>
							<div id="annonceColoc" class="col-md-12">
								<div id="annonceColoc" class="col-md-4 col-sm-4 col-xs-12">
									<div id="photoAnnonce" class="col-md-12 col-sm-12 col-xs-12">
										<div id="photoAnnonce" style="background: url(https://lcdcfrance-prod.s3.amazonaws.com/pictures/1fcfb11b21b7a9b1246992c16d340f7c_medium.jpg) 50% 50% no-repeat;"></div>
									</div>
								</div>
								<div id="divContenDescriptionAnnonce" class="col-md-8 col-sm-8 col-xs-12">
									<div id="descriptionAnnonce" class="col-md-12 col-sm-12 col-xs-12">
										<h4>Maison de 5 collocataires</h4>
										<p class="fontFamilyNote" id="textTopDescriptionArt">1 chambre disponible dès le 11/12/2019</p>
										<div class="flex">
											<div class="flex childFlex divLocalisationAnnonce-alpv">
												<i class="fas fa-map-marker-alt iconLocalisationAnnonce-alpv"></i>
												<p>Rennes</p>
											</div>
										</div>
										<p class="fontFamilyNote" id="textDescriptionArt">
											Nous recherchons 2 hommes pour amener une mixité dans la colocation et qui seraient interressés pour co-habiter avec ...
										</p>
									</div>
								</div>
							</div>
						</div>
					</div>
				</a>
			</div>
		</div>
		<div id="annonce2-alpv" class="divBlocAnnonce1-ereom">
			<div id="divBlocAnnonce2" class="col-sm-12 col-xs-12">
				@if (User.Identity.IsAuthenticated && ViewBag.researchType == "offering")
				{
					<div class="divToolEditAnnonceLocation-alpv">
						<a href="@Url.Action("AddUpd_ModalRentalAd", "Ad_Rental", new { @operation = "Update"})" rel="modal:open" class="linkToolProjetCreation-al">
							<i class="fas fa-pencil-alt childFlex iconToolEditPC-al" id="btnEditProjetCreation-al"></i>
						</a>
						<a href="@Url.Action("Del_MsgModalRentalAd", "Ad_Rental", null)" rel="modal:open" class="linkToolProjetCreation-al">
							<i class="fas fa-trash childFlex iconToolEditPC-al" id="btnRemoveProjetCreation-al"></i>
						</a>
					</div>
				}
				<a id="annonceLocationPVLink-2" href="@Url.Action("Read_ModalRentalAd","Ad_Rental", new { @idModal = "2" })" rel="modal:open">
					<div id="underAnnonce2-alpv" class="col-md-12 col-sm-12 divAnnonceColoc">
						<div id="div2AnnonceColoc" class="col-md-12 col-sm-12 col-xs-12">
							<input id="valueGps10" name="valueGps10" type="hidden" value="46.89, 2.67">
							<div id="divPrixAnnonce">
								<div id="prixAnnonce">340€<span id="rentCosts">/mois</span></div>
							</div>
							<div id="annonceColoc" class="col-md-12">
								<div id="annonceColoc" class="col-md-4 col-sm-4 col-xs-12">
									<div id="photoAnnonce" class="col-md-12 col-sm-12 col-xs-12">
										<div id="photoAnnonce" style="background: url(https://lcdcfrance-prod.s3.amazonaws.com/pictures/1fcfb11b21b7a9b1246992c16d340f7c_medium.jpg) 50% 50% no-repeat;"></div>
									</div>
								</div>
								<div id="divContenDescriptionAnnonce" class="col-md-8 col-sm-8 col-xs-12">
									<div id="descriptionAnnonce" class="col-md-12 col-sm-12 col-xs-12">
										<h4>Maison de 5 collocataires</h4>
										<p class="fontFamilyNote" id="textTopDescriptionArt">2 chambres disponibles dès le 01/08/2020</p>
										<div class="flex">
											<div class="flex childFlex divLocalisationAnnonce-alpv">
												<i class="fas fa-map-marker-alt iconLocalisationAnnonce-alpv"></i>
												<p>Rennes</p>
											</div>
										</div>
										<p class="fontFamilyNote" id="textDescriptionArt">
											Nous recherchons 2 hommes pour amener une mixité dans la colocation et qui seraient interressés pour co-habiter avec ...
										</p>
									</div>
								</div>
							</div>
						</div>
					</div>
				</a>
			</div>
		</div>
		<div id="divOthersAnnounces-alpv" class="overflow"></div>
		<div class="flex">
			<div class="btnGreen childFlex" id="btnOtherAnnonceLocation-alpv" onclick="showOthersLocationAnnounces()">
				<p id="txtShowNewEvent-alpv">Voir plus d'annonces</p>
				<div class="flex"><i class="fas fa-sort-down childFlex" id="iconShowNewEvent-alpv"></i></div>
			</div>
		</div>
	</div>
</div>

<script language="javascript">
	$(document).ready(function () {
		var researchType = "@ViewData["researchType"]"

		if (researchType == "searching") {
			$(".divToolEditAnnonceLocation-alpv").remove();
		}

		copyDivToOtherElement("#divContenerBlocAnnonce", "#lstRentalAd-rad")
	});
</script>