Eco-Colocation/Controllers/EcoColocHomeController.cs
using Eco_Colocation.ViewModel;
using System.Web.Mvc;

namespace Eco_Colocation.Controllers
{
	public class EcoRoommateHomeController : Controller
	{
		public ActionResult EcoRoommateHomeView()
		{
			AllViewModel allViewModel = new AllViewModel();

			PeopleSearchingViewModel peopleSearching = new PeopleSearchingViewModel(true);
			allViewModel.PeopleSearchingVM = peopleSearching;

			for (int i = 0; i < 6; i++)
			{
				peopleSearching = new PeopleSearchingViewModel(true);
				peopleSearching.IdPeopleSearching = i;
				allViewModel.PeopleSearchingVM.LstPeopleSearchingVM.Add(peopleSearching);
			}

			return View(allViewModel);
		}

		public ActionResult TypeRecherche(AllViewModel allViewModel)
		{
			TempData["allViewModel"] = allViewModel;

			return RedirectToAction("CommonAd", new { researchType = allViewModel.EcoRoommateVM.TypeRecherche });
		}

		public ActionResult CommonAd(string currentTab, string researchType, string operation)
		{
			AllViewModel allViewModel = new AllViewModel();
			allViewModel.PeopleSearchingVM = new PeopleSearchingViewModel(true);

			PeopleSearchingViewModel peopleSearching = new PeopleSearchingViewModel(true);
			for (int i = 0; i < 6; i++)
			{
				peopleSearching.IdPeopleSearching = i;
				allViewModel.PeopleSearchingVM.LstPeopleSearchingVM.Add(peopleSearching);
			}

			if (currentTab != null && currentTab.Length != 0)
			{
				ViewData["currentTab"] = currentTab;
			}
			else
			{
				ViewData["currentTab"] = "AnnonceLocation";
			}
			
			ViewData["researchType"] = (researchType != null) ? researchType : "searching";

			ViewData["operation"] = (operation != null) ? operation : "operation";

			return View("~/Views/Ad_Common/RubriqueAd.cshtml", allViewModel);
		}
	}
}

Eco-Colocation/Controllers/EcoRoommateExistingController.cs
using System.Web.Mvc;

namespace Eco_Colocation.Controllers
{
    public class EcoRoommateExistingController : Controller
	{
        // GET: EcoRoommateExisting
        public ActionResult Index()
        {
            return View();
        }

		public ActionResult AddUpd_EcoRoommateExisting(string operation)
		{
			if (operation != null)
			{
				ViewData["operation"] = operation;
			}

			return View();
		}

		public ActionResult ValidAddUpd_EcoRoommateExisting()
		{
			//faire en sort que si l'admin est connecté. Alors nul besoin de remplir de compte eco-coloc.
			return View();
		}
		
		public ActionResult Read_EcoRoommateExisting()
		{
			return View();
		}

		public ActionResult ModalChooseExistingVisual()
		{
			return PartialView();
		}
	}
}

Eco-Colocation/Views/EcoRoommateExisting/Del_MsgModalEcoRoommateExisting.cshtml
@{
	ViewBag.Title = "Del_MsgModalEcoRoommateExisting";
}

<div class="underModal col-sm-12 col-xs-12">
	<div id="Del_MsgModalEcoRoommateExisting" class="reelModal">
		<h2 class="title centerText">Suppression de votre eco-colocation</h2>
		<p id="titleTop-mder">Voulez êtes sur le point de supprimer votre eco-colocation "Colokitri" de la carte. Confirmez-vous l'opération ?</p>
		<div class="flex">
			<div style="margin-left:auto;flex-wrap: wrap;display: flex;">
				<div class="divBtn-mder">
					<a href="#close-modal" rel="modal:close" class="closeModal" id="btnCancelInfo-mder">Annuler</a>
				</div>
				<div class="divBtn-mder">
					<a id="btnDeleteInfo-mder" href="@Url.Action("EcoRoommateHomeView", "EcoRoommateHome", null)">Oui, je confirme</a>
				</div>
			</div>
		</div>
	</div>
</div>

Eco-Colocation/Views/EcoRoommateExisting/EcoRoommateExistingView.cshtml
@{
	/**/

	ViewBag.Title = "EcoRoommateExistingView";
}

<div id="EcoRommateExisting_OnMap">
	<div>
		<div id="title-ereom">Les éco&#8209colocations existantes</div>
		<div id="descEcoRoom-ereom" class="fontFamilyNote">
			Une éco-colocation c'est avant tout une envie de vivre ensemble, de créer un
			mode de vie le plus sain possible pour soi, la communauté et son environnement.
		</div>
	</div>
	<div class="flex" style="
    margin-bottom: 15px;
">
		<div class="divSommaireLogo-ereom">
			<img src="/Content/Images/Logos/markerColocExistingOnMap.png" class="imgSommaireLogo-ereom">
			<p class="fontFamilyNote txtSommaireLogo-ereom">Les éco-colocations existantes</p>

		</div>
		<div class="divSommaireLogo-ereom">
			<img src="/Content/Images/Logos/markerEvenement.png" class="imgSommaireLogo-ereom">
			<p class="fontFamilyNote txtSommaireLogo-ereom">Les événements à venir</p>

		</div>
	</div>
	<div id="divMapEcoRoom-ereom">
		<div id="leafletMap_ereo" class="leaflet-container leaflet-touch leaflet-fade-anim leaflet-grab leaflet-touch-drag leaflet-touch-zoom" tabindex="0">
		</div>
	</div>
</div>

<div class="ecoRommateExisting-ereom" id="ecoColocExistante1">
	<div class="ecoRommateExisting2-ereom">
		<div class="divMarkerPhoto-ereom col-md-5 col-xs-5">
			<div class="markerPhoto-ereom"
				 style="background: url(https://www.domoskit.com/wp-content/uploads/2017/05/matheus-ferrero-228716-unsplash-thegem-blog-default.jpg) 50% no-repeat">
			</div>
		</div>
		<div class="description-ereom col-md-7 col-xs-7">
			<p class="nameColoc-ereom">Colokitri 1</p>@* Facultatif *@
			<div class="infoPrimaire-ereom">
				<p class="fontFamilyNote">4 Colocataire(s)</p>
			</div>
			<p class="descriptionHabitat-ereom fontFamilyNote">Une maison paille, un potager, 5 poules et deux chats et 4 colocataires</p>
		</div>
	</div>
	<div id="divLinkDetailEvent-erevom">
		<a class="linkDetailEvent-erevom" href="@Url.Action("Read_EcoRoommateExisting","EcoRoommateExisting", null)">
			<i id="iconDetailEvent-erevom" class="fas fa-angle-double-right"></i>
			<p class="fontFamilyNote">En savoir plus</p>
		</a>
	</div>
</div>
<div class="ecoRommateExisting-ereom" id="ecoColocExistante2">
	<div class="ecoRommateExisting2-ereom">
		<div class="divMarkerPhoto-ereom col-md-5 col-xs-5">
			<div class="markerPhoto-ereom"
				 style="background: url(https://www.domoskit.com/wp-content/uploads/2017/05/matheus-ferrero-228716-unsplash-thegem-blog-default.jpg) 50% no-repeat">
			</div>
		</div>
		<div class="description-ereom col-md-7 col-xs-7">
			<p class="nameColoc-ereom">Colokitri 2</p>@* Facultatif *@
			<div class="infoPrimaire-ereom">
				<p class="fontFamilyNote">4 Colocataire(s)</p>
			</div>
			<p class="descriptionHabitat-ereom fontFamilyNote">Une maison paille, un potager, 5 poules et deux chats et 4 colocataires</p>
		</div>
	</div>
	<div id="divLinkDetailEvent-erevom">
		<a class="linkDetailEvent-erevom" href="@Url.Action("Read_EcoRoommateExisting","EcoRoommateExisting", null)">
			<i id="iconDetailEvent-erevom" class="fas fa-angle-double-right"></i>
			<p class="fontFamilyNote">En savoir plus</p>
		</a>
	</div>
</div>

<div id="divBtnAddOurEcoRoom-ereom">
	<a id="btnAddOurEcoRoom-ereom" class="btn waves-light waves-effect" href="@Url.Action("AddUpd_EcoRoommateExisting","EcoRoommateExisting")">Ajouter notre éco-colocation</a>
</div>

<script type="text/javascript">
	$(document).ready(function () {
		loadEcoRoommateMap();
	});
</script>

Eco-Colocation/Views/EcoRoommateExisting/EcoRoommateExisting_OnMap.cshtml
@{
	/**/

	ViewBag.Title = "EcoRoommateExisting_OnMap";
}

<div id="EcoRommateExisting_OnMap">
	<div>
		<div id="title-ereom">Les éco&#8209colocations existantes</div>
		<div id="descEcoRoom-ereom" class="fontFamilyNote">
			Une éco-colocation c'est avant tout une envie de vivre ensemble, de créer un
			mode de vie le plus sain possible pour soi, la communauté et son environnement.
		</div>
	</div>
	<div class="flex" style="
    margin-bottom: 15px;
">
		<div class="divSommaireLogo-ereom">
			<img src="/Content/Images/Logos/markerColocExistingOnMap.png" class="imgSommaireLogo-ereom">
			<p class="fontFamilyNote txtSommaireLogo-ereom">Les éco-colocations existantes</p>

		</div>
		<div class="divSommaireLogo-ereom">
			<img src="/Content/Images/Logos/markerEvenement.png" class="imgSommaireLogo-ereom">
			<p class="fontFamilyNote txtSommaireLogo-ereom">Les événements à venir</p>

		</div>
	</div>
	<div id="divMapEcoRoom-ereom">
		<div id="leafletMap_ereo" class="leaflet-container leaflet-touch leaflet-fade-anim leaflet-grab leaflet-touch-drag leaflet-touch-zoom" tabindex="0">
		</div>
	</div>
</div>

<div class="ecoRommateExisting-ereom" id="ecoColocExistante1">
	<div class="ecoRommateExisting2-ereom">
		<div class="divMarkerPhoto-ereom col-md-5 col-xs-5">
			<div class="markerPhoto-ereom"
				 style="background: url(https://www.domoskit.com/wp-content/uploads/2017/05/matheus-ferrero-228716-unsplash-thegem-blog-default.jpg) 50% no-repeat">
			</div>
		</div>
		<div class="description-ereom col-md-7 col-xs-7">
			<p class="nameColoc-ereom">Colokitri 1</p>@* Facultatif *@
			<div class="infoPrimaire-ereom">
				<p class="fontFamilyNote">4 Colocataire(s)</p>
			</div>
			<p class="descriptionHabitat-ereom fontFamilyNote">Une maison paille, un potager, 5 poules et deux chats et 4 colocataires</p>
		</div>
	</div>
	<div id="divLinkDetailEvent-erevom">
		<a class="linkDetailEvent-erevom" href="@Url.Action("Read_EcoRoommateExisting","EcoRoommateExisting", null)">
			<i id="iconDetailEvent-erevom" class="fas fa-angle-double-right"></i>
			<p class="fontFamilyNote">En savoir plus</p>
		</a>
	</div>
</div>
<div class="ecoRommateExisting-ereom" id="ecoColocExistante2">
	<div class="ecoRommateExisting2-ereom">
		<div class="divMarkerPhoto-ereom col-md-5 col-xs-5">
			<div class="markerPhoto-ereom"
				 style="background: url(https://www.domoskit.com/wp-content/uploads/2017/05/matheus-ferrero-228716-unsplash-thegem-blog-default.jpg) 50% no-repeat">
			</div>
		</div>
		<div class="description-ereom col-md-7 col-xs-7">
			<p class="nameColoc-ereom">Colokitri 2</p>@* Facultatif *@
			<div class="infoPrimaire-ereom">
				<p class="fontFamilyNote">4 Colocataire(s)</p>
			</div>
			<p class="descriptionHabitat-ereom fontFamilyNote">Une maison paille, un potager, 5 poules et deux chats et 4 colocataires</p>
		</div>
	</div>
	<div id="divLinkDetailEvent-erevom">
		<a class="linkDetailEvent-erevom" href="@Url.Action("Read_EcoRoommateExisting","EcoRoommateExisting", null)">
			<i id="iconDetailEvent-erevom" class="fas fa-angle-double-right"></i>
			<p class="fontFamilyNote">En savoir plus</p>
		</a>
	</div>
</div>

<div id="divBtnAddOurEcoRoom-ereom">
	<a id="btnAddOurEcoRoom-ereom" class="btn waves-light waves-effect" href="@Url.Action("AddUpd_EcoRoommateExisting","EcoRoommateExisting")">Ajouter notre éco-colocation</a>
</div>

<script type="text/javascript">
	$(document).ready(function () {
		loadEcoRoommateMap();
	});
</script>

Eco-Colocation/Views/EcoRoommateExisting/ModalDeleteEcoRoommate.cshtml
@{
	ViewBag.Title = "ModalDeleteEcoRoommate";
}

<div class="underModal col-sm-12 col-xs-12">
	<div id="modalDeleteEcoRoommate" class="reelModal">
		<h2 id="titleTop-mder">Vous êtes sur le point de supprimer votre eco-colocation "Colokitri" de la carte. Confirmez-vous ?</h2>		
		<div class="flex">
			<div style="margin-left:auto;flex-wrap: wrap;display: flex;">
				<div class="divBtn-mder">
					<a id="btnCancelInfo-mder" href="@Url.Action("AddYourEcoRoommate", "EcoRoommateExisting", null)">Annuler</a>
				</div>
				<div class="divBtn-mder">
					<a id="btnDeleteInfo-mder" href="@Url.Action("Index", "Home", null)">Oui, supprimer</a>
				</div>
			</div>
		</div>
	</div>
</div>

Eco-Colocation/Views/EcoRoommateExisting/ModalDeleteEcoRoommateExisting.cshtml
@{
	ViewBag.Title = "ModalDeleteEcoRoommateExistingExisting";
}

<div class="underModal col-sm-12 col-xs-12">
	<div id="ModalDeleteEcoRoommateExisting" class="reelModal">
		<h2 id="titleTop-mder">Vous êtes sur le point de supprimer votre eco-colocation "Colokitri" de la carte. Confirmez-vous ?</h2>		
		<div class="flex">
			<div style="margin-left:auto;flex-wrap: wrap;display: flex;">
				<div class="divBtn-mder">
					<a href="#close-modal" rel="modal:close" class="closeModal" id="btnCancelInfo-mder" >Annuler</a></div>
				<div class="divBtn-mder">
					<a id="btnDeleteInfo-mder" href="@Url.Action("Index", "Home", null)">Oui, supprimer</a>
				</div>
			</div>
		</div>
	</div>
</div>

Eco-Colocation/Views/EcoRoommateExisting/Read_EcoRoommateExisting.cshtml
@{
	ViewBag.Title = "Read_EcoRoommateExisting";
	ViewBag.urlCurrentPage = "/EcoRoommateExisting/Read_EcoRoommateExisting";
}

<div id="Read_EcoRoommateExisting">
	<p id="titleTop-erev">Colokitri</p>@* Facultatif *@
	@if (User.Identity.IsAuthenticated)
	{
		<div id="divBtnModifierEcoRoom-erev">
			<a id="btnModifierEcoRoom-erev" href="@Url.Action("AddUpd_EcoRoommateExisting", "EcoRoommateExisting", new { @operation = "Update" })">Modifier nos informations</a>
		</div>
	}
	<div id="divTopInfoEcoColoc-erev">
		<div id="divTopInfoEcoColoc2-erev">
			<div class="divRoom-erev col-sm-6 col-xs-12">
				<div class="divTopInfoRoom2-erev">
					<i class="iconTopPage-erev fas fa-users"></i>
					<p class="responseRoom-erev">4 Personnes</p>
				</div>
			</div>
			<div class="divRoom-erev col-sm-6 col-xs-12">
				<div class="divTopInfoRoom2-erev">
					<i class="iconTopPage-erev fas fa-map-marker-alt"></i>
					<p class="responseRoom-erev">Romanier-pondir</p>
				</div>
			</div>
		</div>
	</div>
	@* Valider -Asup *@
	<div id="imgCover-erev">
		<div id="d1-2-btnphoto-mpc" onclick="plusDivs(-1)">
			<img src="/Content/Images/Icons/arrow-left.png">
		</div>
		<div id="d2-1-btnphoto-erev" onclick="plusDivs(+1)">
			<img src="/Content/Images/Icons/arrow-right.png">
		</div>
		<div id="imgRoommate-erev">
			<div class="imgCoverEcoRoommate-erev mySlides" style="background: url(https://www.domoskit.com/wp-content/uploads/2017/05/matheus-ferrero-228716-unsplash-thegem-blog-default.jpg) 50% no-repeat;"></div>
			<div class="imgCoverEcoRoommate-erev mySlides" style="background: url(https://images.lindependant.fr/api/v1/images/view/5cbb6a52d286c24c466b8bc3/large/image.jpg) 50% no-repeat;"></div>
		</div>
	</div>
	<div id="divDescriptionEcoRoom-erev">
		Une maison paille, un potager, 5 poules et deux chats et 4 colocataires pour une vie écologique. Au cœur de Romanier-pondir, notre éco-colocation a vu le jour en Juillet 2016. Elle s'est fondée sur l’envie de vivre ensemble en ayant le minimun d’impacts négatifs possibles sur notre environnement. Nous nous nourrissons essentiellement de produits bio et locaux pour une alimentation majoritairement végétarienne. Le point fort : le jardin ! De plus nos poules offrent quotidiennement des œufs. Nous partons faire nos courses avec sacs en vrac et bocaux que nous nous empressons de remplir dans notre cuisine commune. Qui dit cuisine commune, dit courses communes : nous achetons pour l’ensemble de la colocation et partageons les frais sur un compte commun ou chaque coloc verse sa part du mois. Et qui dit mutualisation dit réduction des coûts, réduction accentuée par la volonté de faire par exemple des économies d’énergie. (Par exemple nous avons troqué notre gros frigo contre un petit et nous envisageons de nous en passer définitivement). Nous avons bien sûr remplacé le maximum d’ampoules possible par des lampes basse consommation et nous tentons de garder au mieux la chaleur pour ne pas allumer les radiateurs. Enfin, notre colocation se fonde sur le vivre ensemble. Nous ne comptons pas ce que nous faisons ou donnons. Ici chaque personne étant libre de son implication, l’essentiel est de s'assurer que tout le monde trouve sa place pour bien vivre ensemble.
	</div>

	<div id="divGlobalBlogInfo-erev">
		<div>
			<h2 class="titleLevel2-erev">
				Niveau d'implication écologique
			</h2>
			<div class="flex">
				<div class="childFlex" id="divLevelTree-erev">
					<i class="fas fa-tree" id="treeLevel1" style="color: #b0bc03;"></i>
					<i class="fas fa-tree" id="treeLevel2" style="color: #b0bc03;"></i>
					<i class="fas fa-tree" id="treeLevel3"></i>
				</div>
			</div>
			<p id="txtFibreEco-erev">"Tenter notre possible pour réduire notre impact environnemental"</p>
		</div>
		<div>
			<h2 class="titleLevel2-erev">
				Ce que l'on y fait écologiquement
			</h2>

			<div class="divGlobalToCenter-erev">
				<div class="divContenantImgInfo-erev">
					<p class="underTitlePratique-erev">Production alimentaire</p>
					<div class="imgLogoRepresentation-erev" style="background: url(/Content/images/logos/agriculture.png) no-repeat;"></div>
					<div class="displayUnderAction-erev">
						<p class="textLevel2ProdAlim-erev">Bio</p>
						<p class="textLevel2ProdAlim-erev">Permaculture</p>
					</div>
				</div>
				<div class="divContenantImgInfo-erev">
					<p class="underTitlePratique-erev">Consommation</p>
					<div class="imgLogoRepresentation-erev" style="background: url(/Content/images/logos/food.png) no-repeat;"></div>
					<div class="displayUnderAction-erev">
						<p class="textLevel2ProdAlim-erev">Bio</p>
						<p class="textLevel2ProdAlim-erev">Végétarien</p>
						<p class="textLevel2ProdAlim-erev">Local</p>
					</div>
				</div>
				<div class="divContenantImgInfo-erev">
					<p class="underTitlePratique-erev">Déplacement</p>
					<div class="imgLogoRepresentation-erev" style="background: url(/Content/images/logos/direction.png) no-repeat;"></div>
					<div class="displayUnderAction-erev">
						<p class="textLevel2ProdAlim-erev">Bus</p>
						<p class="textLevel2ProdAlim-erev">Vélo</p>
						<p class="textLevel2ProdAlim-erev">Marche</p>
					</div>
				</div>

				<div class="divContenantImgInfo-erev">
					<p class="underTitlePratique-erev">Vie en communauté</p>
					<div class="imgLogoRepresentation-erev" style="background: url(/Content/images/logos/people.png) no-repeat;"></div>
					<div class="displayUnderAction-erev">
						<p class="textLevel2ProdAlim-erev">Repas</p>
						<p class="textLevel2ProdAlim-erev">Partage des tâches</p>
					</div>
				</div>
			</div>
			<p class="descriptionSuplementaire-erev">Nous essayons tous de prêter attention du mieux possible à ces différents éléments pour réduire notre impact environnemental</p>
			<h2 class="titleLevel2-erev">
				Ce que l'on a d'écologique chez nous
			</h2>
			<div class="divGlobalToCenter-erev">
				<div class="divContenantImgInfo-erev">
					<div class="imgLogoRepresentation-erev" style="background: url(/Content/images/logos/seed.png) no-repeat;"></div>
					<p class="underTitle-erev">Potager</p>
				</div>
				<div class="divContenantImgInfo-erev">
					<div class="imgLogoRepresentation-erev" style="background: url(/Content/images/logos/recyclingBin.png) no-repeat;"></div>
					<p class="underTitle-erev">Poubelles de recyclage</p>
				</div>
				<div class="divContenantImgInfo-erev">
					<div class="imgLogoRepresentation-erev" style="background: url(/Content/images/logos/compost.png) no-repeat;"></div>
					<p class="underTitle-erev">compost</p>
				</div>
				<div class="divContenantImgInfo-erev">
					<div class="imgLogoRepresentation-erev" style="background: url(/Content/images/logos/toilet.png) no-repeat;"></div>
					<p class="underTitle-erev">Toilette seches</p>
				</div>
				<div class="divContenantImgInfo-erev">
					<div class="imgLogoRepresentation-erev" style="background: url(/Content/images/logos/naturalhouse.png) no-repeat;"></div>
					<p class="underTitle-erev">Habitat en matériaux écologique ou recyclable</p>
				</div>
				<div class="divContenantImgInfo-erev">
					<div class="imgLogoRepresentation-erev" style="background: url(/Content/images/logos/heater.png) no-repeat;"></div>
					<p class="underTitle-erev">Chauffage écologique</p>
				</div>
				<div class="divContenantImgInfo-erev">
					<div class="imgLogoRepresentation-erev" style="background: url(/Content/images/logos/waterRecycling.png) no-repeat;"></div>
					<p class="underTitle-erev">Outils de recyclage des eaux</p>
				</div>

			</div>
			<p class="descriptionSuplementaire-erev">Concernant le chauffage et l'électricité nous utilisons l'énergie produite par les panneaux solaires ainsi que les deux éloliennes installées au fond du jardin.</p>
			<h2 class="titleLevel2-erev">
				Ce que l'on réduit grâce à nos attitudes
			</h2>
			<div class="divGlobalToCenter-erev">
				<div class="divContenantImgInfo-erev">
					<div class="imgLogoRepresentation-erev" style="background: url(/Content/images/logos/waterConsommation.png) no-repeat;"></div>
					<p class="underTitle-erev">Notre consommation d'eau</p>
				</div>
				<div class="divContenantImgInfo-erev">
					<div class="imgLogoRepresentation-erev" style="background: url(/Content/images/logos/electricity.png) no-repeat;"></div>
					<p class="underTitle-erev">Notre consommation d'électricité</p>
				</div>
				<div class="divContenantImgInfo-erev">
					<div class="imgLogoRepresentation-erev" style="background: url(/Content/images/logos/wastConsommation.png) no-repeat;"></div>
					<p class="underTitle-erev">Nos déchets</p>
				</div>
				<div class="divContenantImgInfo-erev">
					<div class="imgLogoRepresentation-erev" style="background: url(/Content/images/logos/consomationCarburant.png) no-repeat;"></div>
					<p class="underTitle-erev">Notre consommation de carburant</p>
				</div>

			</div>
			<p class="descriptionSuplementaire-erev">Nous essayons tous de prêter attention du mieux possible à ces différents éléments pour réduire notre impact environnemental</p>
			<h2 class="titleLevel2-erev">
				Comment est notre habitat
			</h2>
			<div id="divGlobalSuperficieHabitat-erev">
				<div id="divGlobalSuperficieHabitat2-erev">
					<div id="divSuperficieTerrain-erev">
						<p class="txtSuperficie-erev">Superficie du terrain</p>
						<p class="responseSuperficie-erev">400 m²</p>
					</div>
					<div id="divSuperficieHabitat-erev">
						<p class="txtSuperficie-erev">Superficie de l'habitat</p>
						<p class="responseSuperficie-erev">400 m²</p>
					</div>

				</div>
			</div>
			<p id="txtDiversPieces">Les différentes pièces</p>
			<div id="divAllPlace-erev">
				<div id="divAllPlace2-erev">
					<p class="col-xs-6">1 cuisine</p>
					<p class="col-xs-6">1 salle à manger</p>
					<p class="col-xs-6">1 salon</p>
					<p class="col-xs-6">4 chambre</p>
					<p class="col-xs-6">1 toilettes</p>
					<p class="col-xs-6">1 salle de bain</p>
					<p class="col-xs-6">1 bureau</p>
					<p class="col-xs-6">1 jardin</p>
					<p class="col-xs-6">1 terrasse</p>
					<p class="col-xs-6">2 balcon</p>
					<p class="col-xs-6">1 garage</p>
				</div>
			</div>
			<div>
				@if (!User.Identity.IsAuthenticated)
				{
					<div class="divBtnBottom-erev">
						<a id="btnContacter-erev" href="/Account/ModalAccount" rel="modal:open">
							Contacter cette éco-colocation
						</a>
					</div>
				}
				else
				{
					<h2 class="titleLevel2-erev centerText">
						Contacter cette éco-colocation
					</h2>

					<div id="divSendMessage-erev">
						<div id="divSendMessage2-erev">
							@Html.Partial("~/Views/ContactUs/PartialViewMessage.cshtml")
						</div>
					</div>
				}

				<div class="divBtnBottom-erev">
					<a id="btnRetour-erev" href="@Url.Action("EcoRoommateHomeView", "EcoRoommateHome", null)">Retour</a>
				</div>
			</div>
		</div>
	</div>
</div>