Eco-Colocation/Controllers/EcoColocHomeController.cs
using Eco_Colocation.ViewModel;
using System.Web.Mvc;

namespace Eco_Colocation.Controllers
{
	public class EcoRoommateHomeController : Controller
	{
		public ActionResult EcoRoommateHomeView()
		{
			AllViewModel allViewModel = new AllViewModel();

			PeopleSearchingViewModel peopleSearching = new PeopleSearchingViewModel(true);
			allViewModel.PeopleSearchingVM = peopleSearching;

			for (int i = 0; i < 6; i++)
			{
				peopleSearching = new PeopleSearchingViewModel(true);
				peopleSearching.IdPeopleSearching = i;
				allViewModel.PeopleSearchingVM.LstPeopleSearchingVM.Add(peopleSearching);
			}

			return View(allViewModel);
		}

		public ActionResult TypeRecherche(AllViewModel allViewModel)
		{
			TempData["allViewModel"] = allViewModel;

			return RedirectToAction("CommonAd", new { researchType = allViewModel.EcoRoommateVM.TypeRecherche });
		}

		public ActionResult CommonAd(string currentTab, string researchType, string operation)
		{
			AllViewModel allViewModel = new AllViewModel();
			allViewModel.PeopleSearchingVM = new PeopleSearchingViewModel(true);

			PeopleSearchingViewModel peopleSearching = new PeopleSearchingViewModel(true);
			for (int i = 0; i < 6; i++)
			{
				peopleSearching.IdPeopleSearching = i;
				allViewModel.PeopleSearchingVM.LstPeopleSearchingVM.Add(peopleSearching);
			}

			if (currentTab != null && currentTab.Length != 0)
			{
				ViewData["currentTab"] = currentTab;
			}
			else
			{
				ViewData["currentTab"] = "AnnonceLocation";
			}
			
			ViewData["researchType"] = (researchType != null) ? researchType : "searching";

			ViewData["operation"] = (operation != null) ? operation : "operation";

			return View("~/Views/Ad_Common/RubriqueAd.cshtml", allViewModel);
		}
	}
}

Eco-Colocation/Controllers/EcoRoommateEventController.cs
using System.Web.Mvc;
using Eco_Colocation.ViewModel;

namespace Eco_Colocation.Controllers
{
	public class EcoRoommateEventController : Controller
	{
		// GET: EcoRoommateEvent
		public ActionResult Index()
		{
			return View();
		}
		public ActionResult AddUpd_EcoRoommateEvent(string operation)
		{
			if (operation != null)
			{
				ViewData["operation"] = operation;
			}

			return View();
		}

		public ActionResult Read_ModalEcoRoommateEvent(string idModal)
		{
			EcoRoommateEventViewModel EcoRoommateEventViewModel = new EcoRoommateEventViewModel();
			EcoRoommateEventViewModel.Id = 2;

			ViewData["idModal"] = idModal;

			return PartialView();
		}

		public ActionResult Del_MsgModalEcoRoommateEvent()
		{
			return PartialView("~/Views/EcoRoommateEvent/Del_MsgModalEcoRoommateEvent.cshtml");
		}

		public ActionResult ModalGoingOrInterested()
		{
			return PartialView();
		}

		public ActionResult AddPublication()
		{
			return PartialView("~/Views/EcoRoommateEvent/Read_ModalEcoRoommateEvent.cshtml");
		}
	}
}

Eco-Colocation/Views/EcoRoommateEvent/AddUpd_EcoRoommateEvent.cshtml
@{
	ViewBag.Title = "AddUpd_EcoRoommateExistingEvent";
	ViewBag.Operation = ViewData["operation"];
}
<div id="AddUpd_EcoRoommateEvent">
	@if (ViewBag.Operation != "Update")
	{
		<h2 id="titleTop-ayer" class="title">Ajout d'un nouvel événement</h2>
	}
	else
	{
		<h2 id="titleTop-ayer" class="title">Modification de votre événement</h2>
	}
	<div class="divSommaireFormulaire sousDivFormColoc-ayer">
		<div class="flex">
			<p class="etoileObligation">*</p>
			<p class="txtEtoileObligation">Champ obligatoire</p>
		</div>
	</div>
	<div class="overflow flex flexWrap">
		<div class="sousDivFormColoc-ayere">
			<label class="label-ayer">Nom *</label>
			<input class="input-ayer" placeholder="Entrez un nom d'événement" maxlength="70">
			<div class="underInput-ayer"></div>
		</div>
		<div class="sousDivFormColoc-ayere">
			<label class="label-ayer">Date et Heure de début *</label>
			<input class="input-ayer" type="datetime-local">
			<div class="underInput-ayer"></div>
		</div>
		<div class="sousDivFormColoc-ayere">
			<label class="label-ayer">Date et Heure de fin *</label>
			<input class="input-ayer" type="datetime-local">
			<div class="underInput-ayer"></div>
		</div>
		<div class="flex" id="divLocation-ayere">
			<div id="divNumRue-ayere" class="sousDivFormColoc-ayere">
				<label class="label-ayer">N° Rue</label>
				<div class="flex">
					<input type="search" id="numRueInput-ayer" class="form-control">
				</div>
			</div>
			<div id="inputlieu-ayere" class="sousDivFormColoc-ayer">
				<label class="label-ayer">Adresse *</label>
				<input id="inputSearchPlace-ayere" oninput="addr_searchStreet(this);" type="text" class="inputSearchPlace form-control ui-autocomplete-input" placeholder="Où recherchez-vous ?">
				<div class="listAutoCompleteToModal"><ul id="ui-id-1" tabindex="0" class="ui-menu ui-widget ui-widget-content ui-autocomplete ui-front" style="display: none; top: 346.5px; left: 189.5px; width: 530px;"><li class="ui-menu-item"><a id="ui-id-22" tabindex="-1" class="ui-menu-item-wrapper"><i class="iconAutoComplete fas fa-map-marker-alt"></i><strong id="txtLabelAutoCompletion">René Descartes 38230 Charvieu-Chavagneux</strong><p id="txtContextAutoCompletion">38, Isère, Auvergne-Rhône-Alpes</p></a></li><li class="ui-menu-item"><a id="ui-id-23" tabindex="-1" class="ui-menu-item-wrapper"><i class="iconAutoComplete fas fa-map-marker-alt"></i><strong id="txtLabelAutoCompletion">Rene Coty 91330 Yerres</strong><p id="txtContextAutoCompletion">91, Essonne, Île-de-France</p></a></li><li class="ui-menu-item"><a id="ui-id-24" tabindex="-1" class="ui-menu-item-wrapper"><i class="iconAutoComplete fas fa-map-marker-alt"></i><strong id="txtLabelAutoCompletion">René 56130 Férel</strong><p id="txtContextAutoCompletion">56, Morbihan, Bretagne</p></a></li><li class="ui-menu-item"><a id="ui-id-25" tabindex="-1" class="ui-menu-item-wrapper"><i class="iconAutoComplete fas fa-map-marker-alt"></i><strong id="txtLabelAutoCompletion">Rene Tacquet 01510 Artemare</strong><p id="txtContextAutoCompletion">01, Ain, Auvergne-Rhône-Alpes</p></a></li><li class="ui-menu-item"><a id="ui-id-26" tabindex="-1" class="ui-menu-item-wrapper"><i class="iconAutoComplete fas fa-map-marker-alt"></i><strong id="txtLabelAutoCompletion">Rene 33670 Saint-Genès-de-Lombaud</strong><p id="txtContextAutoCompletion">33, Gironde, Nouvelle-Aquitaine</p></a></li></ul></div>
			</div>
		</div>
		<div id="divFacebookLinkEvent-ayere" class="sousDivFormColoc-ayer">
			<label class="label-ayer">Lien lié à l'événement</label>
			<input type="search" id="facebookLinkEvent-ayere" class="form-control" placeholder="Ex : http://www.facebookEvent-01452...">
		</div>
		<div class="col-xs-12 sousDivFormColoc-ayer" style="margin-bottom: 25px;">
			<label class="label-ayer">Description de votre événement *</label>
			<textarea id="txtareaDescColoc-ayer"></textarea>
		</div>
	</div>
	<div class="overflow">
		<div class="col-xs-12">
			<label class="label-ayer">Ajouter une photo à l'image de l'évènement *</label>
			<label id="btnAddPicture-ayer" for="fileUpload-ayer">Ajouter une photo</label>
			<input id="fileUpload-ayer" type="file" onchange="uploadImgEcoRoommate();">
			<div id="divResultFilesUpl-ayer">
				<img src="" id="resultImgUpl-ayer">
				<i id="icondeletePicture-ayer" class="fas fa-times-circle" onclick="removeUploadPicture_ayer()"></i>
				<i class="fas fa-check-circle" id="checkPicture-ayer"></i>
			</div>
		</div>
	</div>
	<h3 class="title centerText" id="titleOtherEvents-ayere">Selectionner les événements associés au votre</h3>

	<div class="flex" id="divContener0OtherEvents-ayere">
		<div id="d1-btnphoto-mpc" class="btnDivOtherEvent-eyere flex">
			<div id="d1-2-btnphoto-mpc" onclick="turnLeftOthersEvents('#divContenerOtherEvents-ayere')">
				<img src="/Content/Images/Icons/arrow-left.png">
			</div>
		</div>
		<div id="d2-btnphoto-ayere" class="btnDivOtherEvent-eyere flex">
			<div id="d2-1-btnphoto-mpc" onclick="turnRightOthersEvents('#divContenerOtherEvents-ayere')">
				<img src="/Content/Images/Icons/arrow-right.png">
			</div>
		</div>
		<div class="flex childFlex" id="divContenerOtherEvents-ayere">
			<div class="flex divElementEvent-ayer">
				<div>
					<div class="divOtherLinkEvent-merev">
						<div onclick="checkedOrNotAccordingToTheStatus('#chbEvent1')">
							<div>
								<p class="titleOtherLinkEvent-merev">Apero Eco-Colocation Strasbourg</p>
								<p class="fontFamilyNote underTitleOLinkEvent-merev">Jeudi 2 Mai 2019</p>
							</div>
							<div class="flex">
								<div style="background: url(https://resize.prod.docfr.doc-media.fr/img/var/doctissimo/storage/images/media/images/fr/www/apero-sain/7764125-1-fre-FR/Apero-sain.jpg) 50% 50% no-repeat;" class="imgOtherLink-merev"></div>
							</div>
						</div>
						<div class="flex">
							<div class="childFlex">
								<input id="chbEvent1" name="CbxEvenement" type="checkbox" value="true"><input name="CbxEvenement" type="hidden" value="false">
							</div>
						</div>
					</div>
				</div>
			</div>
			<div class="flex divElementEvent-ayer">
				<div>
					<div class="divOtherLinkEvent-merev">
						<div onclick="checkedOrNotAccordingToTheStatus('#chbEvent2')">
							<div>
								<p class="titleOtherLinkEvent-merev">Apero Eco-Colocation Lille</p>
								<p class="fontFamilyNote underTitleOLinkEvent-merev">02 Mai - 04 Mai 2019</p>
							</div>
							<div class="flex">
								<div style="background: url(http://img.over-blog-kiwi.com/1/95/94/45/20160405/ob_f9b13f_apero3.jpg) 50% 50% no-repeat;" class="imgOtherLink-merev"></div>
							</div>
						</div>
						<div class="flex">
							<div class="childFlex">
								<input id="chbEvent2" name="CbxEvenement" type="checkbox" value="true"><input name="CbxEvenement" type="hidden" value="false">
							</div>
						</div>
					</div>
				</div>
			</div>
			<div class="flex divElementEvent-ayer">
				<div class="centerOtherEvent-ayere">
					<div class="divOtherLinkEvent-merev">
						<div onclick="checkedOrNotAccordingToTheStatus('#chbEvent3')">
							<div>
								<p class="titleOtherLinkEvent-merev">Apero Eco-Colocation Lyon</p>
								<p class="fontFamilyNote underTitleOLinkEvent-merev">Jeudi 2 Mai 2019</p>
							</div>
							<div class="flex">
								<div style="background: url(https://gentlemanmoderne.com/wp-content/uploads/2017/06/Idee-apero.jpg) 50% 50% no-repeat;" class="imgOtherLink-merev"></div>
							</div>
						</div>
						<div class="flex">
							<div class="childFlex">
								<input id="chbEvent3" name="CbxEvenement" type="checkbox" value="true"><input name="CbxEvenement" type="hidden" value="false">
							</div>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>

	@if (!User.Identity.IsAuthenticated)
	{
		<div id="createAccount-ayere">
			<h2 id="titleValidInscription-ayere" class="title centerText">Valider l'événement en s'inscrivant</h2>
			<p class="underTitle centerText" id="underTitleValidInscri-ayere">uniquement si vous n'avez pas encore de compte</p>
			@Html.Partial("~/Views/Account/PersonalDataForm.cshtml")
		</div>
		@Html.Partial("~/Views/Account/ButtonsCreateAccount.cshtml")
	}

	<div id="divBottomBtn-ayer">
		@if (User.Identity.IsAuthenticated)
		{
			<div class="flex">
				<a id="btnValidateInfo-ayer" href="@Url.Action("EcoRoommateHomeView", "EcoRoommateHome", null)">Valider mes informations</a>
			</div>
		}
		<div class="flex">
			<a id="btnCancelInfo-ayer" href="@Url.Action("EcoRoommateHomeView", "EcoRoommateHome", null)">Retour</a>
		</div>
	</div>

	@* Rajouter des conditions d'affichage *@
	@if (User.Identity.IsAuthenticated)
	{
		<div class="flex">
			<a id="btnSupColoc-ayer" href="@Url.Action("Del_MsgModalEcoRoommateEvent", "EcoRoommateEvent", null)" rel="modal:open">Supprimer l'événement</a>
		</div>
	}
</div>

<script language="javascript">
	$(document).ready(function () {
		checkToShowArrowDivEvents('#divContenerOtherEvents-ayere');
		//Changement d'emplacement du bouton
		
		});
</script>

Eco-Colocation/Views/EcoRoommateEvent/AddYourEcoRoommateEvent.cshtml
@{
	ViewBag.Title = "AddYourEcoRoommateExistingEvent";
}
<div id="addYourEcoRoommateEvent">
	<h2 id="titleTop-ayer" class="title">Ajout d'un nouvel événement</h2>
	<div class="divSommaireFormulaire sousDivFormColoc-ayer">
		<div class="flex">
			<p class="etoileObligation">*</p>
			<p class="txtEtoileObligation">Champ obligatoire</p>
		</div>
	</div>
	<div class="overflow flex flexWrap">
		<div class="sousDivFormColoc-ayere">
			<label class="label-ayer">Nom *</label>
			<input class="input-ayer" placeholder="Entrez un nom d'événement" maxlength="70">
			<div class="underInput-ayer"></div>
		</div>
		<div class="sousDivFormColoc-ayere">
			<label class="label-ayer">Date et Heure de début *</label>
			<input class="input-ayer" type="datetime-local">
			<div class="underInput-ayer"></div>
		</div>
		<div class="sousDivFormColoc-ayere">
			<label class="label-ayer">Date et Heure de fin *</label>
			<input class="input-ayer" type="datetime-local">
			<div class="underInput-ayer"></div>
		</div>
		<div class="flex" id="divLocation-ayere">
			<div id="divNumRue-ayere" class="sousDivFormColoc-ayere">
				<label class="label-ayer">N° Rue</label>
				<div class="flex">
					<input type="search" id="numRueInput-ayer" class="form-control">
				</div>
			</div>
			<div id="inputlieu-ayere" class="sousDivFormColoc-ayer">
				<label class="label-ayer">Adresse *</label>
				<input id="inputSearchPlace-ayere" oninput="addr_searchStreet(this);" type="text" class="inputSearchPlace form-control ui-autocomplete-input" placeholder="Où recherchez-vous ?">
				<div class="listAutoCompleteToModal"><ul id="ui-id-1" tabindex="0" class="ui-menu ui-widget ui-widget-content ui-autocomplete ui-front" style="display: none; top: 346.5px; left: 189.5px; width: 530px;"><li class="ui-menu-item"><a id="ui-id-22" tabindex="-1" class="ui-menu-item-wrapper"><i class="iconAutoComplete fas fa-map-marker-alt"></i><strong id="txtLabelAutoCompletion">René Descartes 38230 Charvieu-Chavagneux</strong><p id="txtContextAutoCompletion">38, Isère, Auvergne-Rhône-Alpes</p></a></li><li class="ui-menu-item"><a id="ui-id-23" tabindex="-1" class="ui-menu-item-wrapper"><i class="iconAutoComplete fas fa-map-marker-alt"></i><strong id="txtLabelAutoCompletion">Rene Coty 91330 Yerres</strong><p id="txtContextAutoCompletion">91, Essonne, Île-de-France</p></a></li><li class="ui-menu-item"><a id="ui-id-24" tabindex="-1" class="ui-menu-item-wrapper"><i class="iconAutoComplete fas fa-map-marker-alt"></i><strong id="txtLabelAutoCompletion">René 56130 Férel</strong><p id="txtContextAutoCompletion">56, Morbihan, Bretagne</p></a></li><li class="ui-menu-item"><a id="ui-id-25" tabindex="-1" class="ui-menu-item-wrapper"><i class="iconAutoComplete fas fa-map-marker-alt"></i><strong id="txtLabelAutoCompletion">Rene Tacquet 01510 Artemare</strong><p id="txtContextAutoCompletion">01, Ain, Auvergne-Rhône-Alpes</p></a></li><li class="ui-menu-item"><a id="ui-id-26" tabindex="-1" class="ui-menu-item-wrapper"><i class="iconAutoComplete fas fa-map-marker-alt"></i><strong id="txtLabelAutoCompletion">Rene 33670 Saint-Genès-de-Lombaud</strong><p id="txtContextAutoCompletion">33, Gironde, Nouvelle-Aquitaine</p></a></li></ul></div>
			</div>
		</div>
		<div id="divFacebookLinkEvent-ayere" class="sousDivFormColoc-ayer">
			<label class="label-ayer">Lien lié à l'événement</label>
			<input type="search" id="facebookLinkEvent-ayere" class="form-control" placeholder="Ex : http://www.facebookEvent-01452...">
		</div>
		<div class="col-xs-12 sousDivFormColoc-ayer" style="margin-bottom: 25px;">
			<label class="label-ayer">Description de votre événement *</label>
			<textarea id="txtareaDescColoc-ayer"></textarea>
		</div>
	</div>
	<div class="overflow">
		<div class="col-xs-12">
			<label class="label-ayer">Ajouter une photo à l'image de l'évènement *</label>
			<label id="btnAddPicture-ayer" for="fileUpload-ayer">Ajouter une photo</label>
			<input id="fileUpload-ayer" type="file" onchange="uploadImgEcoRoommate();">
			<div id="divResultFilesUpl-ayer">
				<img src="" id="resultImgUpl-ayer">
				<i id="icondeletePicture-ayer" class="fas fa-times-circle" onclick="removeUploadPicture_ayer()"></i>
				<i class="fas fa-check-circle" id="checkPicture-ayer"></i>
			</div>
		</div>
	</div>
	<h3 class="title centerText" id="titleOtherEvents-ayere">Selectionner les événements associés au votre</h3>

	<div class="flex" id="divContener0OtherEvents-ayere">
		<div id="d1-btnphoto-mpc" class="btnDivOtherEvent-eyere flex">
			<div id="d1-2-btnphoto-mpc" onclick="turnLeftOthersEvents('#divContenerOtherEvents-ayere')">
				<img src="/Content/Images/Icons/arrow-left.png">
			</div>
		</div>
		<div id="d2-btnphoto-ayere" class="btnDivOtherEvent-eyere flex">
			<div id="d2-1-btnphoto-mpc" onclick="turnRightOthersEvents('#divContenerOtherEvents-ayere')">
				<img src="/Content/Images/Icons/arrow-right.png">
			</div>
		</div>
		<div class="flex childFlex" id="divContenerOtherEvents-ayere">
			<div class="flex divElementEvent-ayer">
				<div>
					<div class="divOtherLinkEvent-merev">
						<div onclick="checkedOrNotAccordingToTheStatus('#chbEvent1')">
							<div>
								<p class="titleOtherLinkEvent-merev">Apero Eco-Colocation Strasbourg</p>
								<p class="fontFamilyNote underTitleOLinkEvent-merev">Jeudi 2 Mai 2019</p>
							</div>
							<div class="flex">
								<div style="background: url(https://www.izroom.com/blog/wp-content/uploads/2017/06/ap%C3%A9ro-2.jpg) 50% 50% no-repeat;" class="imgOtherLink-merev"></div>
							</div>
						</div>
						<div class="flex">
							<div class="childFlex">
								<input id="chbEvent1" name="CbxEvenement" type="checkbox" value="true"><input name="CbxEvenement" type="hidden" value="false">
							</div>
						</div>
					</div>
				</div>
			</div>
			<div class="flex divElementEvent-ayer">
				<div>
					<div class="divOtherLinkEvent-merev">
						<div onclick="checkedOrNotAccordingToTheStatus('#chbEvent2')">
							<div>
								<p class="titleOtherLinkEvent-merev">Apero Eco-Colocation Lille</p>
								<p class="fontFamilyNote underTitleOLinkEvent-merev">02 Mai - 04 Mai 2019</p>
							</div>
							<div class="flex">
								<div style="background: url(http://img.over-blog-kiwi.com/1/95/94/45/20160405/ob_f9b13f_apero3.jpg) 50% 50% no-repeat;" class="imgOtherLink-merev"></div>
							</div>
						</div>
						<div class="flex">
							<div class="childFlex">
								<input id="chbEvent2" name="CbxEvenement" type="checkbox" value="true"><input name="CbxEvenement" type="hidden" value="false">
							</div>
						</div>
					</div>
				</div>
			</div>
			<div class="flex divElementEvent-ayer">
				<div class="centerOtherEvent-ayere">
					<div class="divOtherLinkEvent-merev">
						<div onclick="checkedOrNotAccordingToTheStatus('#chbEvent3')">
							<div>
								<p class="titleOtherLinkEvent-merev">Apero Eco-Colocation Lyon</p>
								<p class="fontFamilyNote underTitleOLinkEvent-merev">Jeudi 2 Mai 2019</p>
							</div>
							<div class="flex">
								<div style="background: url(https://gentlemanmoderne.com/wp-content/uploads/2017/06/Idee-apero.jpg) 50% 50% no-repeat;" class="imgOtherLink-merev"></div>
							</div>
						</div>
						<div class="flex">
							<div class="childFlex">
								<input id="chbEvent3" name="CbxEvenement" type="checkbox" value="true"><input name="CbxEvenement" type="hidden" value="false">
							</div>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>

	@if (!User.Identity.IsAuthenticated)
	{
		<div id="createAccount-ayere">
			<h2 id="titleValidInscription-ayere" class="title centerText">Valider l'événement en s'inscrivant</h2>
			<p class="underTitle centerText" id="underTitleValidInscri-ayere">uniquement si vous n'avez pas encore de compte</p>
			@Html.Partial("~/Views/Account/PersonalDataForm.cshtml")
		</div>
		@Html.Partial("~/Views/Account/ButtonsCreateAccount.cshtml")
	}

	<div id="divBottomBtn-ayer">
		@if (User.Identity.IsAuthenticated)
		{
			<div class="flex">
				<a id="btnValidateInfo-ayer" href="@Url.Action("Index", "Home", null)">Valider mes informations</a>
			</div>
		}
		<div class="flex">
			<a id="btnCancelInfo-ayer" href="@Url.Action("Index", "Home", null)">Retour</a>
		</div>
	</div>

	@* Rajouter des conditions d'affichage *@
	@if (User.Identity.IsAuthenticated)
	{
		<div class="flex">
			<a id="btnSupColoc-ayer" href="@Url.Action("ModalDeleteEcoRoommateEvent", "EcoRoommateEvent", null)" rel="modal:open">Supprimer l'événement</a>
		</div>
	}
</div>

<script language="javascript">
	$(document).ready(function () {
		checkToShowArrowDivEvents('#divContenerOtherEvents-ayere');
		//Changement d'emplacement du bouton
	});
</script>

Eco-Colocation/Views/EcoRoommateEvent/Del_MsgModalEcoRoommateEvent.cshtml
@{
	ViewBag.Title = "Del_MsgModalEcoRoommateEvent";
}

<div class="underModal col-sm-12 col-xs-12">
	<div id="Del_MsgModalEcoRoommateExisting" class="reelModal">
		<h2 id="titleTop-mder">Suppression de votre évenement</h2>
		<h2 id="titleTop-mder">Vous êtes sur le point de supprimer l'événement du site web. Confirmez-vous l'opération ?</h2>
		<div class="flex">
			<div style="margin-left:auto;flex-wrap: wrap;display: flex;">
				<div class="divBtn-mder">
					<a href="#close-modal" rel="modal:close" class="closeModal" id="btnCancelInfo-mder">Annuler</a>
				</div>
				<div class="divBtn-mder">
					<a id="btnDeleteInfo-mder" href="@Url.Action("EcoRoommateHomeView", "EcoRoommateHome", null)">Oui, je confirme</a>
				</div>
			</div>
		</div>
	</div>
</div>

Eco-Colocation/Views/EcoRoommateEvent/ModalDeleteEcoRoommateEvent.cshtml
@{
	ViewBag.Title = "ModalDeleteEcoRoommateEvent";
}

<div class="underModal col-sm-12 col-xs-12">
	<div id="ModalDeleteEcoRoommateExisting" class="reelModal">
		<h2 id="titleTop-mder">Suppression de votre évenement</h2>
		<h2 id="titleTop-mder">Vous êtes sur le point de supprimer l'événement du site web. Confirmez-vous l'opération ?</h2>
		<div class="flex">
			<div style="margin-left:auto;flex-wrap: wrap;display: flex;">
				<div class="divBtn-mder">
					<a href="#close-modal" rel="modal:close" class="closeModal" id="btnCancelInfo-mder">Annuler</a>
				</div>
				<div class="divBtn-mder">
					<a id="btnDeleteInfo-mder" href="@Url.Action("Index", "Home", null)">Oui, je confirme</a>
				</div>
			</div>
		</div>
	</div>
</div>